create type Status AS enum ('Pending', 'In-Progress', 'Complete');

create type Priority AS enum('Low', 'Medium', 'High');

create type Role AS enum('Owner', 'User');

create table public."Avatars" (
  "AvatarID" bigint generated by default as identity not null,
  "imageURL" text not null,
  "XPRequired" integer null,
  constraint Avatars_pkey primary key ("AvatarID")
) TABLESPACE pg_default;

create table public."Users" (
  "userID" bigint generated by default as identity not null,
  "firstName" text null default ''::text,
  "lastName" text null default ''::text,
  email text null default ''::text,
  phone text null default ''::text,
  "totalXP" smallint not null default '1'::smallint,
  constraint Users_pkey primary key ("userID"),
  constraint Users_UserID_key unique ("userID")
) TABLESPACE pg_default;

create table public."Quests" (
  "questID" bigint generated by default as identity not null,
  "questName" text not null default ''::text,
  "questDetails" text not null default ''::text,
  "dueDate" timestamp with time zone not null,
  "completionDate" timestamp with time zone null,
  "XP" bigint not null,
  status public.status not null default 'Pending'::status,
  priority public.priority not null default 'Low'::priority,
  constraint Quests_pkey primary key ("questID"),
  constraint Quests_QuestID_key unique ("questID")
) TABLESPACE pg_default;

create table public."Projects" (
  "projectID" bigint generated by default as identity not null,
  "projectTitle" text not null,
  description text not null,
  "creationDate" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  "ownerID" bigint not null,
  "dueDate" timestamp with time zone null,
  status public.status not null default 'Pending'::status,
  constraint Projects_pkey primary key ("projectID"),
  constraint Projects_ProjectID_key unique ("projectID"),
  constraint Projects_ownerID_fkey foreign KEY ("ownerID") references "Users" ("userID") on update CASCADE
) TABLESPACE pg_default;

create table public."ProjectMembers" (
  "userID" bigint generated by default as identity not null,
  "projectID" bigint generated by default as identity not null,
  role public.role not null default 'User'::role,
  constraint ProjectMembers_pkey primary key ("userID", "projectID"),
  constraint ProjectMembers_projectID_fkey foreign KEY ("projectID") references "Projects" ("projectID") on update CASCADE,
  constraint ProjectMembers_userID_fkey foreign KEY ("userID") references "Users" ("userID") on update CASCADE
) TABLESPACE pg_default;

create table public."QuestAssignments" (
  "userID" bigint generated by default as identity not null,
  "questID" bigint not null,
  "assignedDate" timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  constraint QuestAssignments_pkey primary key ("userID"),
  constraint QuestAssignments_questID_fkey foreign KEY ("questID") references "Quests" ("questID") on update CASCADE on delete CASCADE,
  constraint QuestAssignments_userID_fkey foreign KEY ("userID") references "Users" ("userID") on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public."UserAvatars" (
  "userID" bigint generated by default as identity not null,
  "avatarID" bigint not null,
  "unlockedDate" timestamp with time zone null default now(),
  "isActive" boolean not null default false,
  constraint UserAvatars_pkey primary key ("userID"),
  constraint UserAvatars_avatarID_fkey foreign KEY ("avatarID") references "Avatars" ("AvatarID") on update CASCADE on delete set null,
  constraint UserAvatars_userID_fkey foreign KEY ("userID") references "Users" ("userID") on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public."XPLog" (
  "LogID" bigint generated by default as identity not null,
  "userID" bigint not null,
  "questID" bigint null,
  "timeStamp" timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  constraint XPLog_pkey primary key ("LogID"),
  constraint XPLog_questID_fkey foreign KEY ("questID") references "Quests" ("questID") on update CASCADE,
  constraint XPLog_userID_fkey foreign KEY ("userID") references "Users" ("userID") on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

